---
title: 'A02: Professor Diamond Data Regression Models'
author: "Cadence Fisher"
date: '2022-03-26'
slug: a02-professor-diamond-data-regression-models
categories: []
tags: []
---
```{r}
library(readr)
library(readxl)
library(tidyverse)
library(dplyr)
library(ggplot2)

```

```{r}
diamonds <- read_excel("/Users/cfish/Downloads/Professor_Proposes_Data.xlsx")
diamonds
```
```{r}
attach(diamonds)
```


```{r}
colnames(diamonds)
```

# Converting the Data to Metric
```{r}
library(caret)
```

```{r}
dummy1 <- dummyVars("~ .", data = diamonds)
diamonds_mod <- data.frame((predict(dummy1, newdata = diamonds)))
diamonds_mod
```


# Graphing the Data
## Carat
```{r}
lm(Price ~ Carat, data = diamonds_mod)
```

```{r}
ggplot(diamonds_mod,aes(Carat, Price)) +
  geom_point() +
  geom_smooth(method='lm', se=FALSE, color='turquoise4') +
  theme_minimal() +
  labs(x='Carat', y='Price', title='Plot of Carat v.s. Price') +
  theme(plot.title = element_text(hjust=0.5, size=20, face='bold')) 
```
Splitting Price into higher and lower:
```{r}
range(Price)
```

```{r}
diamonds_low <- diamonds_mod[diamonds_mod$Price < 1500,]
diamonds_high <- diamonds_mod[diamonds_mod$Price > 1500,]

```
## Color
```{r}
lm(Price ~ Colour, data = diamonds_mod)
```

```{r}
lm(Price ~ Colour, data = diamonds_mod)
```
```{r}
diamonds_low %>% mutate_all(~replace(., is.na(.), 0))
glimpse(diamonds_low)
```


```{r}
library(ggpubr)
```

```{r}
colourd <- ggplot(diamonds_low, aes(ColourD, Price)) + geom_point() 
coloure <- ggplot(diamonds_low, aes(ColourE, Price)) + geom_point()
colourf<- ggplot(diamonds_low, aes(ColourF, Price)) + geom_point()
colourg<- ggplot(diamonds_low, aes(ColourG, Price)) + geom_point()
colourh <- ggplot(diamonds_low, aes(ColourH, Price)) + geom_point()
colouri <- ggplot(diamonds_low, aes(ColourI, Price)) + geom_point()
colourj <- ggplot(diamonds_low, aes(ColourJ, Price)) + geom_point()
colourk<- ggplot(diamonds_low, aes(ColourK, Price)) + geom_point()

colours <- ggarrange(coloure,colourf,colourg,  colourh,colouri,colourj, colourk) + geom_smooth(method='lm', se=FALSE) + labs(x='Colour', y='Price', title='Plot of Colour v.s. Price')
```
## Clarity
```{r}
lm(Price ~ Clarity, data = diamonds_mod)
```
```{r}
ggplot(diamonds_mod, aes(Clarity, Price)) +
  geom_point(aes(color = Clarity)) +
  geom_smooth(method='lm', se=FALSE, color='red') +
  theme_minimal() +
  labs(x='Clarity', y='Price', title='Plot of Clarity v.s. Price') +
  theme(plot.title = element_text(hjust=0.5, size=20, face='bold')) 
```
# Cut
```{r}
lm(Price ~ Cut, data = diamonds_mod)
```
```{r}
ggplot(diamonds_mod,aes(Cut, Price)) +
  geom_point() +
  geom_smooth(method='lm', se=FALSE, color='turquoise4') +
  theme_minimal() +
  labs(x='Cut', y='Price', title='Plot of Cut v.s. Price') +
  theme(plot.title = element_text(hjust=0.5, size=20, face='bold')) 
```
# Certification
```{r}
lm(Price ~ Certification, data = diamonds_mod)
```

```{r}
ggplot(diamonds_mod,aes(Certification, Price)) +
  geom_point() +
  geom_smooth(method='lm', se=FALSE, color='blue') +
  theme_minimal() +
  labs(x='Clarity', y='Price', title='Plot of Certification v.s. Price') +
  theme(plot.title = element_text(hjust=0.5, size=20, face='bold')) 
```
# Polish
```{r}
lm(Price ~ Polish, data = diamonds_mod)
```

```{r}
ggplot(diamonds_mod,aes(Polish, Price)) +
  geom_point() +
  geom_smooth(method='lm', se=FALSE, color='green') +
  theme_minimal() +
  labs(x='Polish', y='Price', title='Plot of Polish v.s. Price') +
  theme(plot.title = element_text(hjust=0.5, size=20, face='bold')) 
```
# Symmetry
```{r}
lm(Price ~ Symmetry, data = diamonds_mod)
```

```{r}
ggplot(diamonds_mod,aes(Symmetry, Price)) +
  geom_point() +
  geom_smooth(method='lm', se=FALSE, color='turquoise4') +
  theme_minimal() +
  labs(x='Symmetry', y='Price', title='Plot of Symmetry v.s. Price') +
  theme(plot.title = element_text(hjust=0.5, size=20, face='bold')) 
```

